language: python
python:
  - "2.7"
#  - "3.5"
envs:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py27-django111
#  - TOX_ENV=py34-django18
#  - TOX_ENV=py34-django19
#  - TOX_ENV=py34-django110
#  - TOX_ENV=py34-django111
#  - TOX_ENV=py35-django18
#  - TOX_ENV=py35-django19
#  - TOX_ENV=py35-django110
#  - TOX_ENV=py35-django111
script:
  tox -e {TOX_ENV}
install:
  - pip install tox
